### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by masbou** [WinUICommunity/WinUICommunity-Templates#1]
Thanks for your great software. Do you plan to add Localisation features to the templates.

**Comment by ghost1372** [comment]
Thanks.
Do you mean DynamicLanguage?
Good sugestion

**Comment by masbou** [comment]
> Thanks. Do you mean DynamicLanguage? Good sugestion

Yes like in TVTime

**Comment by ghost1372** [comment]
Hi @masbou 
i uploaded new version v3.0.0:
this is a huge update with awesome features:

![WinUICommunityTemplates](https://raw.githubusercontent.com/WinUICommunity/Resources/main/WinUICommunity-Templates/Wizard1.png)

![WinUICommunityTemplates](https://raw.githubusercontent.com/WinUICommunity/Resources/main/WinUICommunity-Templates/Wizard2.png)
