### ISSUE TITLE
await menuService.SaveAsync(menu); System.InvalidOperationException:“Operation is not valid due to the current state of the object.”

### ISSUE THREAD

**Issue by scx1125** [WinUICommunity/WinUICommunity-Templates#10]
await menuService.SaveAsync(menu);
Crash here.
System.InvalidOperationException:“Operation is not valid due to the current state of the object.”

**Comment by ghost1372** [comment]
Please follow the documentation
https://winuicommunity.github.io/winUICommunityContextMenuExtensions/

Do you use unpackaged mode? If yes, this needs package identity and only works in packaged mode.
