### ISSUE TITLE
.net 8

### ISSUE THREAD

**Issue by Petrarca181** [WinUICommunity/WinUICommunity-Templates#2]
Very cool templates!  .net 8 is missing one thing in .cproj ` <UseRidGraph>true</UseRidGraph>` . At least in my case impossible to compile without it.

**Comment by ghost1372** [comment]
Hi @Petrarca181 
Thank you for the report, I will fix in next version

**Comment by ghost1372** [comment]
@Petrarca181  fixed in v4.3.1
