### ISSUE TITLE
HRESULT E_FAIL

### ISSUE THREAD

**Issue by Petrarca181** [WinUICommunity/WinUICommunity-Templates#3]
Hello, last visual studio, last templates version. Happens on different pcs. 
![image](https://github.com/WinUICommunity/WinUICommunity-Templates/assets/54235138/189b91a1-6855-493d-a436-fb6c9f926859)

Project is still created correctly and works, just the wizard is unable to close visual studio creation window.

update: 
for me happens on  mvvm + navigation + all pages

**Comment by ghost1372** [comment]
> Hello, last visual studio, last templates version. Happens on different pcs. 
> ![image](https://github.com/WinUICommunity/WinUICommunity-Templates/assets/54235138/189b91a1-6855-493d-a436-fb6c9f926859)
> 
> Project is still created correctly and works, just the wizard is unable to close visual studio creation window.
> 
> update: 
> for me happens on  mvvm + navigation + all pages

What is your vs version?
I am using v18.0-preview1 and everything is working fine

**Comment by Petrarca181** [comment]
> > Hello, last visual studio, last templates version. Happens on different pcs.
> > ![image](https://user-images.githubusercontent.com/54235138/285170549-189b91a1-6855-493d-a436-fb6c9f926859.png)
> > Project is still created correctly and works, just the wizard is unable to close visual studio creation window.
> > update:
> > for me happens on  mvvm + navigation + all pages
> 
> What is your vs version? I am using v18.0-preview1 and everything is working fine

17.8 stable

**Comment by ghost1372** [comment]
I should install vs and test it.

**Comment by ghost1372** [comment]
@Petrarca181 i tested multiple times and projects created without any issues

**Comment by Petrarca181** [comment]
> @Petrarca181 i tested multiple times and projects created without any issues

MVVM + Navigation template
Platform => Add Json Settings => Uncheck
Pages => Add any page

this triggers the error for me.

**Comment by ghost1372** [comment]
@Petrarca181  VSIX development in VS is weak and uses old format/Framework😖
anyway, I was unable to reproduce your issue. I tried every mode and the project created without issues.
However, I had issues with the vsix on my machine and it was causing problems for debugging and testing in VS stable and preview version.  I changed the vsix sdk's (Microsoft.VisualStudio.SDK and Microsoft.VSSDK.BuildTools) and the problems I was having seem to be fixed and now i can debug and test without any issues.
Therefore, use this new version and see if your problem is solved or not?
[WinUICommunity_VS_Templates.zip](https://github.com/WinUICommunity/WinUICommunity-Templates/files/13464883/WinUICommunity_VS_Templates.zip)

**Comment by Petrarca181** [comment]
> @Petrarca181 VSIX development in VS is weak and uses old format/Framework😖 anyway, I was unable to reproduce your issue. I tried every mode and the project created without issues. However, I had issues with the vsix on my machine and it was causing problems for debugging and testing in VS stable and preview version. I changed the vsix sdk's (Microsoft.VisualStudio.SDK and Microsoft.VSSDK.BuildTools) and the problems I was having seem to be fixed and now i can debug and test without any issues. Therefore, use this new version and see if your problem is solved or not? [WinUICommunity_VS_Templates.zip](https://github.com/WinUICommunity/WinUICommunity-Templates/files/13464883/WinUICommunity_VS_Templates.zip)

Same.

**Comment by ghost1372** [comment]
> > @Petrarca181 VSIX development in VS is weak and uses old format/Framework😖 anyway, I was unable to reproduce your issue. I tried every mode and the project created without issues. However, I had issues with the vsix on my machine and it was causing problems for debugging and testing in VS stable and preview version. I changed the vsix sdk's (Microsoft.VisualStudio.SDK and Microsoft.VSSDK.BuildTools) and the problems I was having seem to be fixed and now i can debug and test without any issues. Therefore, use this new version and see if your problem is solved or not? [WinUICommunity_VS_Templates.zip](https://github.com/WinUICommunity/WinUICommunity-Templates/files/13464883/WinUICommunity_VS_Templates.zip)
> 
> Same.

hmmm...
i think you should activate activitylog for vs or clone source code and debug it yourself. because i am unable to repro

**Comment by Petrarca181** [comment]
> > > @Petrarca181 VSIX development in VS is weak and uses old format/Framework😖 anyway, I was unable to reproduce your issue. I tried every mode and the project created without issues. However, I had issues with the vsix on my machine and it was causing problems for debugging and testing in VS stable and preview version. I changed the vsix sdk's (Microsoft.VisualStudio.SDK and Microsoft.VSSDK.BuildTools) and the problems I was having seem to be fixed and now i can debug and test without any issues. Therefore, use this new version and see if your problem is solved or not? [WinUICommunity_VS_Templates.zip](https://github.com/WinUICommunity/WinUICommunity-Templates/files/13464883/WinUICommunity_VS_Templates.zip)
> > 
> > 
> > Same.
> 
> hmmm... i think you should activate activitylog for vs or clone source code and debug it yourself. because i am unable to repro

I will se. isn't HRESULT E_FAIL  related to wasdk elevation problems?

**Comment by ghost1372** [comment]
> > > > @Petrarca181 VSIX development in VS is weak and uses old format/Framework😖 anyway, I was unable to reproduce your issue. I tried every mode and the project created without issues. However, I had issues with the vsix on my machine and it was causing problems for debugging and testing in VS stable and preview version. I changed the vsix sdk's (Microsoft.VisualStudio.SDK and Microsoft.VSSDK.BuildTools) and the problems I was having seem to be fixed and now i can debug and test without any issues. Therefore, use this new version and see if your problem is solved or not? [WinUICommunity_VS_Templates.zip](https://github.com/WinUICommunity/WinUICommunity-Templates/files/13464883/WinUICommunity_VS_Templates.zip)
> > > 
> > > 
> > > Same.
> > 
> > 
> > hmmm... i think you should activate activitylog for vs or clone source code and debug it yourself. because i am unable to repro
> 
> I will se. isn't HRESULT E_FAIL related to wasdk elevation problems?

i removed all wasdk dependency from vsix. i dont know, also try this:

Go to this path:

%appdata%Local\Microsoft\VisualStudio

go to vs folders and remove extensions cache:

ComponentModelCache

and inside Extensions folder remove all related folders.
remove vsix and install again

**Comment by Petrarca181** [comment]
> > > > > @Petrarca181 VSIX development in VS is weak and uses old format/Framework😖 anyway, I was unable to reproduce your issue. I tried every mode and the project created without issues. However, I had issues with the vsix on my machine and it was causing problems for debugging and testing in VS stable and preview version. I changed the vsix sdk's (Microsoft.VisualStudio.SDK and Microsoft.VSSDK.BuildTools) and the problems I was having seem to be fixed and now i can debug and test without any issues. Therefore, use this new version and see if your problem is solved or not? [WinUICommunity_VS_Templates.zip](https://github.com/WinUICommunity/WinUICommunity-Templates/files/13464883/WinUICommunity_VS_Templates.zip)
> > > > 
> > > > 
> > > > Same.
> > > 
> > > 
> > > hmmm... i think you should activate activitylog for vs or clone source code and debug it yourself. because i am unable to repro
> > 
> > 
> > I will se. isn't HRESULT E_FAIL related to wasdk elevation problems?
> 
> i removed all wasdk dependency from vsix. i dont know, also try this:
> 
> Go to this path:
> 
> %appdata%Local\Microsoft\VisualStudio
> 
> go to vs folders and remove extensions cache:
> 
> ComponentModelCache
> 
> and inside Extensions folder remove all related folders. remove vsix and install again

Fixed! Thank you.

**Comment by ghost1372** [comment]
> > > > > > @Petrarca181 VSIX development in VS is weak and uses old format/Framework😖 anyway, I was unable to reproduce your issue. I tried every mode and the project created without issues. However, I had issues with the vsix on my machine and it was causing problems for debugging and testing in VS stable and preview version. I changed the vsix sdk's (Microsoft.VisualStudio.SDK and Microsoft.VSSDK.BuildTools) and the problems I was having seem to be fixed and now i can debug and test without any issues. Therefore, use this new version and see if your problem is solved or not? [WinUICommunity_VS_Templates.zip](https://github.com/WinUICommunity/WinUICommunity-Templates/files/13464883/WinUICommunity_VS_Templates.zip)
> > > > > 
> > > > > 
> > > > > Same.
> > > > 
> > > > 
> > > > hmmm... i think you should activate activitylog for vs or clone source code and debug it yourself. because i am unable to repro
> > > 
> > > 
> > > I will se. isn't HRESULT E_FAIL related to wasdk elevation problems?
> > 
> > 
> > i removed all wasdk dependency from vsix. i dont know, also try this:
> > Go to this path:
> > %appdata%Local\Microsoft\VisualStudio
> > go to vs folders and remove extensions cache:
> > ComponentModelCache
> > and inside Extensions folder remove all related folders. remove vsix and install again
> 
> Fixed! Thank you.

😅 excelent
