### ISSUE TITLE
Would it be possible to add a Winui compatable library or test project? 

### ISSUE THREAD

**Issue by AlexanderBlackman** [WinUICommunity/WinUICommunity-Templates#5]
WASDK 1.5 has allowed new Winui compatible test projects.
Could you add an option to create one in your wizard? The SDK isn't out for Visual Studio yet.

**Comment by ghost1372** [comment]
> WASDK 1.5 has allowed new Winui compatible test projects.
> Could you add an option to create one in your wizard? The SDK isn't out for Visual Studio yet.

Good suggestion tnx

**Comment by ghost1372** [comment]
@AlexanderBlackman i added UnitTest Project Template, you can now Update VSIX and use UnitTest Project Template.
https://github.com/WinUICommunity/WinUICommunity-Templates/releases/tag/v7.2.0
![image](https://github.com/WinUICommunity/WinUICommunity-Templates/assets/9213496/bd09b0c0-7b5a-4fa9-bcd3-6cd805709eaf)


![image](https://github.com/WinUICommunity/WinUICommunity-Templates/assets/9213496/72cd78df-6039-4d17-9f62-9e81213e1914)

**Comment by AlexanderBlackman** [comment]
Great  I can confirm it works, with  a fresh solution, but only works with an existing non-generated solution if I disable editorconfig generation.

Thank you for making this

**Comment by ghost1372** [comment]
> Great  I can confirm it works, with  a fresh solution, but only works with an existing non-generated solution if I disable editorconfig generation.
> 
> Thank you for making this
> 

A video/Gif can be useful if there is any issues.
So i can fix it.

**Comment by AlexanderBlackman** [comment]
It was just a silly mistake on my part, I tried to add it to an existing solution.
