### ISSUE TITLE
Why did I choose a lot of nuget sdk packages, but these packages were not automatically added after the template was created, and the previous version was OK

### ISSUE THREAD

**Issue by scx1125** [WinUICommunity/WinUICommunity-Templates#6]
Why did I choose a lot of nuget sdk packages, but these packages were not automatically added after the template was created, and the previous version was OK

**Comment by scx1125** [comment]
Only these basic packages
![image](https://github.com/WinUICommunity/WinUICommunity-Templates/assets/34766580/237de219-50ee-4c69-96ee-a68f2d6959d0)

**Comment by ghost1372** [comment]
Can you give me a gif/video?
I need to know which packages you choose and which template you are using

**Comment by ghost1372** [comment]
Fixed in https://github.com/WinUICommunity/WinUICommunity-Templates/commit/2920727ecb7e949b0ce5f625393a45a54caac12b
Update to latest version
tnx for report

https://github.com/WinUICommunity/WinUICommunity-Templates/releases/tag/v7.6.0
